### ISSUE TITLE
[BUG] Crash on TCL

### ISSUE THREAD

**Issue by ThallusXu** [giejay/Immich-Android-TV#58]
**Describe the bug**
Crash immediately after connecting to the server.
If connected to the server, it works well. Tried either connect via API key or phone. 

**To Reproduce**
1. Connect to the server.
2. Photos show up and crashes in a second.

**Expected behavior**
Normally work.

**Screenshots**
NA.

**My setup (please complete the following information):**
 - Android OS version: 11
 - Device: TCL  55Q750G
 - Immich app version 1.37

**Additional context**
Log captured by logcat
10-15 22:20:25.681 11151 11185 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
10-15 22:20:25.681 11151 11185 E AndroidRuntime: Process: nl.giejay.android.tv.immich, PID: 11151
10-15 22:20:25.681 11151 11185 E AndroidRuntime: java.lang.IllegalArgumentException: Comparison method violates its general contract!
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at java.util.TimSort.mergeHi(TimSort.java:899)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at java.util.TimSort.mergeAt(TimSort.java:516)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at java.util.TimSort.mergeCollapse(TimSort.java:439)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at java.util.TimSort.sort(TimSort.java:245)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at java.util.Arrays.sort(Arrays.java:1424)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at kotlin.collections.ArraysKt___ArraysJvmKt.sortWith(_ArraysJvm.kt:2179)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at kotlin.collections.CollectionsKt___CollectionsKt.sortedWith(_Collections.kt:1075)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at nl.giejay.android.tv.immich.album.AlbumFragment.sortItems(AlbumFragment.kt:34)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at nl.giejay.android.tv.immich.shared.fragment.VerticalCardGridFragment$setData$2.invokeSuspend(VerticalCardGridFragment.kt:225)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at nl.giejay.android.tv.immich.shared.fragment.VerticalCardGridFragment$setData$2.invoke(Unknown Source:8)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at nl.giejay.android.tv.immich.shared.fragment.VerticalCardGridFragment$setData$2.invoke(Unknown Source:4)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at nl.giejay.android.tv.immich.shared.fragment.VerticalCardGridFragment.setData(VerticalCardGridFragment.kt:224)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at nl.giejay.android.tv.immich.shared.fragment.VerticalCardGridFragment.access$setData(VerticalCardGridFragment.kt:41)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at nl.giejay.android.tv.immich.shared.fragment.VerticalCardGridFragment$setupViews$2.invokeSuspend(VerticalCardGridFragment.kt:221)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:967)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:104)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:250)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7848)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1002)
10-15 22:20:25.681 11151 11185 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@cd45a8a, Dispatchers.IO]

**Comment by ThallusXu** [comment]
Let it sit for a few days and now it works well.
